name: Docker-CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 16.x
      - name: Build and test
        run: |
          docker-compose up -d --build
          docker-compose run backend npm run test
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: mydb
          POSTGRES_PORT: 5432
          POSTGRES_HOST: db
          RABBITMQ_URL: amqp://user:password@rabbitmq:5672/vhost
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672

    services:
      docker:
        image: docker:20.10.9-dind
        ports:
          - 2375:2375
        options: >-
          --privileged
          --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock

