name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
          docker-compose run backend npm run test
          docker-compose down
